config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   ,
  :omniauth_callbacks => 'users/omniauth_callbacks'
  } 
  devise_scope :user do
    get 'user/:id',     to: 'users/registrations#detail'
    get 'signup',       to: 'users/registrations#new'
    get 'login',        to: 'users/sessions#new'
    get 'logout',       to: 'users/sessions#destroy'
  end

  resources :form
  #HomeController
  root 'home#top'
  get '/top',           to: 'home#top'
  get '/readme',        to: 'home#readme'

  #PostsController
  get '/new',           to: 'posts#new'
  post '/create',       to: 'posts#create'
  post '/confirm',      to: 'posts#confirm'
  get '/done',          to: 'posts#done'
  get '/index',         to: 'posts#index'
  get '/index_urgent',  to: 'posts#index_urgent'
  get '/index_today',   to: 'posts#index_today'
  get 'posts/:id',           to: 'posts#show'
  post 'posts/:id/solved',   to: 'posts#solved'
  post 'posts/:id/unsolved', to: 'posts#unsolved'
  get 'posts/:id/update',    to: 'posts#update'
  post 'posts/:id/edit',     to: 'posts#edit'
  resources :posts, only: [:create, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:readme]

  def top
    @posts = Post.all.order(created_at: :desc)
  end

  def readme
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/readme.html.erb
<ul>
  <li>
    <p>
      ・これはT.K.のポートフォリオです。<br><br>
      ・お客様のお問い合わせ送信画面と送信内容の管理画面という作りになっています。<br>
        サービスの目的としては、BtoCの事業の問題・課題を管理しやすくすることを目的としています。<br>
        データの例としては、とあるスーパーマーケットにおける導入されたケースを想定しております。<br><br>
      ・ログインフォームには簡便のためあらかじめidとパスワードが入力されております。<br>
        本来は限られたメンバーのみがidとパスワードを知っているという想定でご確認ください。<br><br>
    </p>
    <%= link_to('ログイン画面へ戻る', '/login') %>
  </li>
</ul>

app/views/home/top.html.erb
<!-- flashメッセージ -->
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<h1 class="cp_h1title">管理者画面トップ</h1>
<!--ここにテキストを入れるとflashの下になる -->
<br><br>
<ul>
  <li>
    <h2>
      <%= link_to("お問い合わせ一覧", index_path) %>
    </h2>
  </li>
  <li>
    <h2>
      <%= link_to("本日寄せられたお問い合わせ", index_today_path) %>
    </h2>
  </li>
  <li>
    <h2>
      <%= link_to("お急ぎのお問い合わせ（未解決）", index_urgent_path) %>
    </h2>
  </li>
  <h2>以下、直近のお問い合わせ一覧</h2>
  <% @posts.first(5).each  do |post| %>
    <ul><li>
      <%= post.created_at.strftime('%Y/%m/%d') %>
      <%= link_to(post.summary, "/posts/#{post.id}") %>
      <% if post.done_flag == true %>
        <b><font color="#ff0000">解決済み</font></b>
      <%end%>
    </li></ul>
    <br>
  <% end %>
  <li>
    <h2>
      <%= link_to("お問い合わせ画面（確認用）", new_path) %>
    </h2>
    <h2>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    </h2>
  </li>
</ul>