config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'   ,
  :omniauth_callbacks => 'users/omniauth_callbacks'
  } 
  devise_scope :user do
    get 'user/:id',     to: 'users/registrations#detail'
    get 'signup',       to: 'users/registrations#new'
    get 'login',        to: 'users/sessions#new'
    get 'logout',       to: 'users/sessions#destroy'
  end

  resources :form
  #HomeController
  root 'home#top'
  get '/top',           to: 'home#top'
  get '/readme',        to: 'home#readme'

  #PostsController
  get '/new',           to: 'posts#new'
  post '/create',       to: 'posts#create'
  post '/confirm',      to: 'posts#confirm'
  get '/done',          to: 'posts#done'
  get '/index',         to: 'posts#index'
  get '/index_urgent',  to: 'posts#index_urgent'
  get '/index_today',   to: 'posts#index_today'
  get 'posts/:id',           to: 'posts#show'
  post 'posts/:id/solved',   to: 'posts#solved'
  post 'posts/:id/unsolved', to: 'posts#unsolved'
  get 'posts/:id/update',    to: 'posts#update'
  post 'posts/:id/edit',     to: 'posts#edit'
  resources :posts, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  validates :summary, {presence: true, length: {maximum: 30}}
  validates :detail, {presence: true, length: {maximum: 400}}
  validates :deal_with_policy, {presence: true, length: {maximum: 50}}
  validates :deal_with_policy, {presence: true, length: {maximum: 600}}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_user
  before_action :authenticate_user!, {only:
    [:index, :index_today, :index_urgent, :solved, :unsolved, :destroy, :show, :edit, :update]}
   
  def new
    @post = Post.new
  end
  
  def confirm
    @post = Post.new(
      urgency: params[:urgency],
      summary: params[:summary],
      detail: params[:detail])
    render("/posts/new") if @post.invalid?
  end
  
  def create
    @post = Post.new(
      urgency: params[:urgency],
      summary: params[:summary],
      detail: params[:detail])
    @post.save
    redirect_to("/done")
  end
  
  def done
    @post = Post.find_by(id: params[:id])
  end
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def index_today
    @posts = Post.where(created_at: Time.zone.now.all_day).order(created_at: :desc)
  end
  
  def index_urgent
    @posts = Post.where(urgency: 3).where(done_flag: 0).order(created_at: :desc)
  end
  
  def show
    @post = Post.find_by(id: params[:id])
  end
  
  def solved
    @post = Post.find_by(id: params[:id])
    @post.done_flag = true
    @post.save
    redirect_to("/posts/#{params[:id]}")
  end
  
  def unsolved
    @post = Post.find_by(id: params[:id])
    @post.done_flag = false
    @post.save
    redirect_to("/posts/#{params[:id]}")
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to(index_path)
  end
  
  def update
    @post = Post.find_by(id: params[:id])
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
    @post.deal_with_policy = params[:deal_with_policy]
    @post.deal_with_detail = params[:deal_with_detail]
    @post.save
    redirect_to("/posts/#{params[:id]}")
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/confirm.html.erb
<h1 class="cp_h1title">お問い合わせ内容の確認</h1>

<ul>
  <li>
    <%= form_tag("/create") do %>
      <h2>
        <p>以下の内容で送信します。よろしいでしょうか？</p>
      </h2>

      <h3>緊急度</h3>
        <% if @post.urgency == 3 %> 
          <%= "ただちに改善を要する事項について" %>
        <% elsif @post.urgency == 2 %>
          <%= "ご希望、またはご要望について" %>
        <% else @post.urgency == 1 %>
          <%= "そのほかについて" %>
        <% end %>
      <br>
      <input id ="input_none" input name = "urgency" value = <%=@post.urgency%>></input>
      
      <h3>概要</h3>
        <%= @post.summary %><br>
        <input id ="input_none" input name = "summary" value = <%=@post.summary%>></input>

      <h3>詳細</h3>
        <%= @post.detail %><br>
        <textarea id ="textarea_none" textarea name = "detail"><%=@post.detail%></textarea><br>
        <input id = "submit_button" input type="submit" value="送信する">
        
    <% end %><p></p>
    <input id = "submit_button" input type="button" value= "戻る" onclick="history.back();">
  </li>
</ul>

app/views/posts/done.html.erb
<h1 class="cp_h1title">お問い合わせを送信しました</h1>
<ul>
  <li>
    貴重なご意見を寄せていただきまことにありがとうございます。
    速やかに調査・検討を行います。
  </li>
</ul>

<%= link_to("お問い合わせフォームへ戻る",new_path) %>

app/views/posts/index.html.erb
<!--flashメッセージ-->
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<h1 class="cp_h1title">お問い合わせ一覧</h1>
<br><br>
<%= link_to("管理者画面トップへ",top_path) %>
<% @posts.each do |post| %>
  <ul>
    <li>
      <%= post.created_at.strftime('%Y/%m/%d') %>
      <%= link_to(post.summary, "/posts/#{post.id}") %>
      <% if post.done_flag == true%>
        <b><font color="#ff0000">解決済み</font></b>
      <%end%>
    </li>
  </ul>
<% end %>

app/views/posts/index_today.html.erb
<h1 class="cp_h1title">本日寄せられたお問い合わせ</h1>
<%= link_to("管理者画面トップへ",top_path) %>
<% if @posts.empty? != true%>
  <% @posts.each do |post| %>
    <ul><li>
      <%= post.created_at.strftime('%Y/%m/%d') %>
      <%= link_to(post.summary, "/posts/#{post.id}") %>
      <% if post.done_flag == true %>
        <b><font color="#ff0000">解決済み</b>
      <%end%>
    </li></ul>
  <% end %>
<% else %>
  <p>※本日寄せられたお問い合わせは、今のところありません。</p>   
<% end %>

app/views/posts/index_urgent.html.erb
<h1 class="cp_h1title">お急ぎのお問い合わせ（未解決）一覧</h1>
<%= link_to("管理者画面トップへ",top_path) %>
<% if @posts.empty? != true%>
  <p>※お急ぎのお問い合わせのうち、未解決のものを表示しています。</p>
  <% @posts.each do |post| %>
    <ul><li>
      <%= post.created_at.strftime('%Y/%m/%d') %>
      <%= link_to(post.summary, "/posts/#{post.id}") %>
    </li></ul>
  <% end %>
<% else %>
  <p>※現在未解決の緊急のお問い合わせはありません。</p>   
<% end %>

app/views/posts/new.html.erb
<h1 class="cp_h1title">ご意見、ご要望をお寄せください</h1>
<br><br>
<!-- flashメッセージ -->
<% if @post.errors.full_messages %>
  <% @post.errors.full_messages.each do |message| %>
    <div class="flash">
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- 入力フォーム -->
<%= form_tag("/confirm") do %>
  <ul>
    <li>
      <h2>どのようなご意見でしょうか？</h2>
      <select id ="post_select" select name="urgency">
        <option value= 3 >ただちに改善を要する事項について</option>    
        <option value= 2 >ご希望、またはご要望について</option>
        <option value= 1 >そのほかについて</option>
      </select>
    </li>
    <li>
      <h2>ご意見の概要</h2>
      <p>※30文字以内でご入力ください</p>
      <input name = "summary"></input>
    </li>
    <li>
      <h2>ご意見の詳細</h2>
      <p>※400文字以内でご入力ください</p>
      <textarea id="post_form" textarea name = "detail"></textarea>
    </li>
    <li>
      <input id="submit_button" input type="submit" value="送信">
    </li>
  </ul>
<% end %>

<!--おことわり-->
<p>お寄せいただいたご意見は、サービスの改善以外の用途には決して使用しません<br>
お客様のプライバシー情報は慎重かつ適切に取り扱います</p>
<% if user_signed_in? %>
  <%= link_to("管理者画面トップへ",top_path)%>
<% end %>

app/views/posts/show.html.erb
<h1 class="cp_h1title">お問い合わせ詳細</h1>
<%= link_to('一覧へ戻る', 'javascript:history.back()') %>
&nbsp;
<%= link_to("管理者画面トップへ","/")%>
<br><br>
<ul>
  <div class="cp_blockdesign02">
    <li>
      <div class="cp_authorname">
        <h2>
          <%=@post.summary%>
          <% if @post.done_flag == true%>
            <b><font size="3.5" color="#ff0000">解決済み</font></b>
          <%end%>
        </h2>
      </div>
    </li>
    <div class="cp_authorinfo">
      <%= @post.detail%>
      <br><br>
      <%= "投稿日時：" %>
      <%=  @post.created_at.strftime('%Y/%m/%d %H:%M')%>
      &nbsp;
      <% if @post.done_flag == true%>
        <%= link_to("未解決に戻す","/posts/#{@post.id}/unsolved", {method: "post"})%>
      <% else %>
        <%= link_to("解決済みにする","/posts/#{@post.id}/solved",{method: "post"})%>
      <%end%>
    </div>
  </div>
</ul>
<br><br><br>
<ul>
  <div class="cp_blockdesign02">
    <div class="cp_authorname">
      <h2>
        <%= "対応：" %>
        <%=@post.deal_with_policy%>
      </h2>
    </div>
    <div class="cp_authorinfo">
      <%= @post.deal_with_detail%>
      <br><br>
      <%= "最終更新日時：" %>
      <%=  @post.updated_at.strftime('%Y/%m/%d %H:%M')%>
      &nbsp;
      <%= link_to("コメントする","/posts/#{@post.id}/update")%>
    </div>
  </div>
</ul>
<br>
<%= link_to("投稿を削除する", post_path, method: :delete, data: { confirm: '削除しますか？' })%>

app/views/posts/update.html.erb
<h1 class="cp_h1title">対応方針編集</h1>

<%= link_to("一覧に戻る",index_path) %>
<br></br>

<div class="cp_blockdesign02">
  <ul>
    <div class="cp_authorname">
      <h2>
        <%=@post.summary%>
        <% if @post.done_flag == true%>
          <b><font size="3.5" color="#ff0000">解決済み</font></b>
        <%end%>
      </h2>
    </div>
    <div class="cp_authorinfo">
      <%= @post.detail%>
      <br><br>
      <%= "投稿日時：" %>
      <%=  @post.created_at.strftime('%Y/%m/%d %H:%M')%>
    </div>
  </ul>
</div>
<br><br><br>

<div class="cp_blockdesign02">
  <ul>
    <%= form_tag("/posts/#{@post.id}/edit") do %>
      <div class="cp_authorname">    
        <h2>
          <%= "対応：" %>
          <input name = "deal_with_policy"value="<%= @post.deal_with_policy %>"></input>
        </h2>
      </div>
      <div class="cp_authorinfo">
        <textarea id="comment_form" textarea name = "deal_with_detail"><%= @post.deal_with_detail%></textarea>
        <br><br>
        <%= "最終更新日時：" %>
        <%=  @post.updated_at.strftime('%Y/%m/%d %H:%M')%>
        &nbsp;
        <input id="submit_button" input type="submit" value="保存">
      </div>
    <% end %>
  </ul>
</div>
<br>